### PR TITLE
Serve over https feature

### LINKED ISSUE #10: Option to run the server with HTTPS protocol
is there a way we can launch the host in `https` mode?

### PR DESCRIPTION
**Pull request by karthilxg**
This PR resolves #10 

- Added option to serve over `HTTPS`, by default the server will start over`HTTP` mode.
- Updated `README` doc with `https` certs and keys configurations.
- Some minor changes to rewrite ES5 code to ES6.

### CODE REVIEW

**Comment by thgh** [comment]
Cool! 👍 

The documentation looks clear except for mentioning HTTP/2. As far as I can find in the nodejs documentation, this PR uses [HTTPS](https://nodejs.org/api/https.html) while [HTTP/2](https://nodejs.org/api/http2.html) is still experimental.

As for spaces/tabs: I wish to keep [standard formatting](https://standardjs.com/).  
We can discuss ES5 => ES6 in another issue, but I would say: 'If it ain't broke, don't fix it'.

**Comment by karthilxg** [comment]
@thgh Ok, make sense!! will update the PR.

**Comment by karthilxg** [comment]
@thgh I have updated the code as per the comments, take a look. Thanks!!

**Comment by karthilxg** [comment]
@thgh Updated the PR by fixing the comments, take a look. Thanks!

**Comment by thgh** [comment]
Great! I will publish on npm this weekend.

**Pull request merged**
